## logging
logging:
  # Logger-specific levels.
  level: INFO
  loggers:
    com.devendra: DEBUG
    io.dropwizard: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
greeting: Hey
username: test
password: test